DROP DATABASE IF EXISTS ACADEMIA;
CREATE DATABASE ACADEMIA;
USE ACADEMIA ;
CREATE TABLE PAGOS(
	Id_Pagos INT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	NUMERO_RECIBO VARCHAR (30) NOT NULL,
	FECHA_PAGO DATE NOT NULL, 
	VALOR_PAGO FLOAT NOT NULL,
	ID_USUARIO_ESTUDIANTE BIGINT NOT NULL
);

CREATE TABLE USUARIO(
	ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	INICIO_SESION VARCHAR (50) NOT NULL,
	CONTRASEÑA VARCHAR(20) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
	ID_PERFIL BIGINT NOT NULL,
	ID_TERCERO BIGINT
);

CREATE TABLE PERFIL(
	ID_PERFIL BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOMBRE_PERFIL VARCHAR(30) NOT NULL

);

CREATE TABLE TERCERO (
	ID_TERCERO BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOMBRES VARCHAR(30) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	TIPO_DOC VARCHAR(30) NOT NULL, 
	NUM_DOC  INT NOT NULL,
	TELEFONO INT,
	CELULAR INT,
	EMAIL VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(30) NOT NULL
);

CREATE TABLE ACUDIENTE(
	ID_ACUDIENTE BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	RELACION_ESTUDIANTE VARCHAR(20) NOT NULL,
	ID_TERCERO BIGINT NOT NULL,
	ID_USUARIO_ESTUDIANTE BIGINT NOT NULL

);

CREATE TABLE HOJA_VIDA_ESTUDIANTIL(
	ID_HOJA_VIDA_ESTUDIANTIL BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOTA_DEFINITIVA SMALLINT NOT NULL, 
	APROBO CHAR(1) NOT NULL,
	ID_CURSO_ASIGNADO BIGINT NOT NULL,
	ID_USUARIO_ESTUDIANTE BIGINT NOT NULL

);

CREATE TABLE CURSO_ASIGNADO(
	ID_CURSO_ASIGNADO BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	CODIDO_CURSO VARCHAR(20) NOT NULL,
	DIAS VARCHAR(50) NOT NULL,
	HORA_INICIO TIME NOT NULL,
	HORA_FIN TIME NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	CUPOS_DISPONIBLES INT NOT NULL,
	ID_USUARIO_PROFESOR BIGINT NOT NULL,
	ID_CURSO BIGINT NOT NULL
);

CREATE TABLE CURSO(
	ID_CURSO BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOMBRE_CURSO VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE NOTA(
	ID_NOTA BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NOMBRE_NOTA VARCHAR(30) NOT NULL,
	VALOR_NOTA SMALLINT NOT NULL,
	PORCENTAJE_NOTA FLOAT NOT NULL,
	DESCRIPCION_NOTA VARCHAR(30) NOT NULL,
	ID_USUARIO_ESTUDIANTE BIGINT NOT NULL,
	ID_CURSO_ASIGNADO BIGINT NOT NULL
);

ALTER TABLE PAGOS ADD FOREIGN KEY(ID_USUARIO_ESTUDIANTE)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE USUARIO ADD FOREIGN KEY(ID_TERCERO)
REFERENCES TERCERO(ID_TERCERO);

ALTER TABLE USUARIO ADD FOREIGN KEY(ID_PERFIL)
REFERENCES PERFIL(ID_PERFIL);

ALTER TABLE ACUDIENTE ADD FOREIGN KEY(ID_TERCERO)
REFERENCES TERCERO(ID_TERCERO);

ALTER TABLE ACUDIENTE ADD FOREIGN KEY(ID_USUARIO_ESTUDIANTE)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE HOJA_VIDA_ESTUDIANTIL ADD FOREIGN KEY(ID_USUARIO_ESTUDIANTE)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE HOJA_VIDA_ESTUDIANTIL ADD FOREIGN KEY(ID_CURSO_ASIGNADO)
REFERENCES CURSO_ASIGNADO(ID_CURSO_ASIGNADO);

ALTER TABLE CURSO_ASIGNADO ADD FOREIGN KEY(ID_USUARIO_PROFESOR)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE CURSO_ASIGNADO ADD FOREIGN KEY(ID_CURSO)
REFERENCES CURSO(ID_CURSO);

ALTER TABLE NOTA ADD FOREIGN KEY(ID_USUARIO_ESTUDIANTE)
REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE NOTA ADD FOREIGN KEY(ID_CURSO_ASIGNADO)
REFERENCES CURSO_ASIGNADO(ID_CURSO_ASIGNADO);